image: docker:latest
services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay
  TAG_LATEST: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:latest
  TAG_COMMIT: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:$CI_COMMIT_SHORT_SHA

stages:
  - build
  - package
  - deploy


maven-build:
  image: maven:3-openjdk-11-slim
  stage: build
  script: "mvn package -B"
  artifacts:
    paths:
      - target/*.jar

docker-build:
  stage: package
  script:    
    - docker build -t $TAG_COMMIT -t $TAG_LATEST .
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker push $TAG_COMMIT
    - docker push $TAG_LATEST


deploy:
  stage: deploy
  tags:
    - deployment
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker pull $TAG_COMMIT
    - docker container rm -f pickup_backend || true
    - docker run -e "SPRING_PROFILES_ACTIVE=prod" -d -p 3333:3333 --name pickup_backend --network backend_default $TAG_COMMIT
  environment:
    name: production
    url: http://bdaf21-owerlen.enterpriselab.ch
  only:
    - master
